### PR TITLE
Make GraphNode.To work for types inheriting from JToken.

### PR DESCRIPTION
**Pull request by danielcweber**
It's reasonable that users will want the underlying JToken (we do!) and the fix is pretty simple.

### CODE REVIEW

**Comment by jorgebay** [comment]
I understand it can be tempting to enable `JToken` conversions but exposing third party types (Json.NET types in this case) from our API is something we actively want to avoid (avoid tight coupling).

**Comment by danielcweber** [comment]
Is there a way to get raw json data from your driver? I see how DseSession gets the json it but the GraphNode class hides it.

**Comment by jorgebay** [comment]
There isn't a way and it's intentional. It's a way to protect the user against protocol format changes.

The latest DSE Graph already supports GraphSON2 which is an entirely different format (and have several improvements over GraphSON1) and we will be able support it with the same public API.

**Comment by danielcweber** [comment]
We agree with that policy. Would you discourage the use of 3rd party libraries to access Gremlin through the standard protocol on port 8182 for any reason? We still want to use your provided driver (and participate in open source) though but have to workaround some issues to get the data out of GraphNodes.

**Comment by jorgebay** [comment]
I haven't looked at other Gremlin drivers closely, make sure it features request pipelining.

Let us know which data you are not able to extract using the current API, we are committed to provide the best user experience possible.

**Comment by danielcweber** [comment]
Would you agree to merge a PR adding a `object To(Type type)` overload to the existing `T To<T>` to GraphNode? I'm currently implementing a fluent gremlin api and some simple ORM. When it comes to JSON arrays, I cannot access the generic overload of `To` for the element type of `T` when `T` is an array (at least not without reflection). I have checked it, the underlying JToken supports it out of the box and the change seems simple. Shouldn't take me long.

**Comment by jorgebay** [comment]
Sorry I'm not sure I understand, can you provide a code snippet showing the usage?
Something like:

```csharp
Vertex vertex = rs.First();
// continue from here
var another = vertex.To(...);
```

**Comment by danielcweber** [comment]
It's rather for when GraphNode wraps a scalar, not a vertex:

    GraphNode node = rs.First();
    // continue from here
    var another = node.To(typeof(int)); // instead of node.To<int>()

**Comment by jorgebay** [comment]
Ah, you mean provide an additional method with a signature that doesn't rely on generics. I think I understand the use case (ie: runtime mapping of values): I don't see why not.

BTW: We are planning to provide a fluent gremlin API based on a C# Gremlin variant [see TinkerPop mailing list discussion][1] and [ticket on TinkerPop JIRA][2].
Also, just for us to track: Are you a DataStax customer or under the Startup program?

[1]: https://lists.apache.org/thread.html/d450e382cd21bba0cb4608e7427d1aec7d51bbc54e58a6169308d8c6@%3Cdev.tinkerpop.apache.org%3E
[2]: https://issues.apache.org/jira/browse/TINKERPOP-1552

**Comment by danielcweber** [comment]
We (@ExRam) are currently under the Startup program.

**Comment by danielcweber** [comment]
I haven't be aware of the ongoing effort to implement a fluent api. Thanks for the hint.

**Comment by danielcweber** [comment]
Opened #50.

**Pull request closed without merging**
